source 'https://github.com/noughts/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'




target 'NNUtils', :exclusive => true do
  pod "NNUtils", :path => "../"
  pod "FrameAccessor"
  pod "NBULog"
end


target 'DrawerDemo', :exclusive => true do
	pod "NNUtils", :path => "../"
	pod "FrameAccessor"
	pod "NBULog"
	pod "NNNotificationController"
end


target 'Tests', :exclusive => true do
  pod "NNUtils", :path => "../"
end
